CREATE USER 'kang'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'kang'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON *.* TO 'kang'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'kang'@'%';

CREATE DATABASE market DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;